Updated start up script
k8-proxy/aws-jmeter-test-engine-v1 pull request #49
Opened 2020-10-16 12:42 UTC by jpoolGW

Edited AMI to run chmod on start up script
Updated JSON file for the Grafana Dashboard

2020-10-16 14:28 UTC, NadHodeGW commented on jmeter-icap-poc/scripts/ICAP-Dashboard-4-grafana.json
> +          "alias": "Total Upload Errors",
We did change this to "Total Process Errors"

2020-10-16 14:30 UTC, NadHodeGW requested changes
See comment; please update the "alias": "Total Upload Errors" to "alias": "Total Process Errors"

2020-10-16 18:57 UTC, DinisCruz approved these changes

2020-10-19 08:30 UTC, jpoolGW commented on jmeter-icap-poc/scripts/ICAP-Dashboard-4-grafana.json
> +          "alias": "Total Upload Errors",
Titles were updated, but not aliases as these weren't displayed on dash. I have now updated the aliases

2020-10-19 18:45 UTC, NadHodeGW approved these changes

2020-10-20 09:00 UTC, merged